package com.bawei.zhujinru.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.zhujinru.model.Dao.GsonDao;
import com.bawei.zhujinru.model.Dao.HomeDao;

import com.bawei.zhujinru.database.GsonDaoDao;
import com.bawei.zhujinru.database.HomeDaoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gsonDaoDaoConfig;
    private final DaoConfig homeDaoDaoConfig;

    private final GsonDaoDao gsonDaoDao;
    private final HomeDaoDao homeDaoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gsonDaoDaoConfig = daoConfigMap.get(GsonDaoDao.class).clone();
        gsonDaoDaoConfig.initIdentityScope(type);

        homeDaoDaoConfig = daoConfigMap.get(HomeDaoDao.class).clone();
        homeDaoDaoConfig.initIdentityScope(type);

        gsonDaoDao = new GsonDaoDao(gsonDaoDaoConfig, this);
        homeDaoDao = new HomeDaoDao(homeDaoDaoConfig, this);

        registerDao(GsonDao.class, gsonDaoDao);
        registerDao(HomeDao.class, homeDaoDao);
    }
    
    public void clear() {
        gsonDaoDaoConfig.clearIdentityScope();
        homeDaoDaoConfig.clearIdentityScope();
    }

    public GsonDaoDao getGsonDaoDao() {
        return gsonDaoDao;
    }

    public HomeDaoDao getHomeDaoDao() {
        return homeDaoDao;
    }

}
