package com.bawei.zhujinru.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawei.zhujinru.model.Dao.GsonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GSON_DAO".
*/
public class GsonDaoDao extends AbstractDao<GsonDao, Void> {

    public static final String TABLENAME = "GSON_DAO";

    /**
     * Properties of entity GsonDao.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property S = new Property(0, String.class, "s", false, "S");
    }


    public GsonDaoDao(DaoConfig config) {
        super(config);
    }
    
    public GsonDaoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GSON_DAO\" (" + //
                "\"S\" TEXT);"); // 0: s
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GSON_DAO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, GsonDao entity) {
        stmt.clearBindings();
 
        String s = entity.getS();
        if (s != null) {
            stmt.bindString(1, s);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, GsonDao entity) {
        stmt.clearBindings();
 
        String s = entity.getS();
        if (s != null) {
            stmt.bindString(1, s);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public GsonDao readEntity(Cursor cursor, int offset) {
        GsonDao entity = new GsonDao( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // s
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, GsonDao entity, int offset) {
        entity.setS(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(GsonDao entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(GsonDao entity) {
        return null;
    }

    @Override
    public boolean hasKey(GsonDao entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
